create table if not exists users
(
    id       bigint primary key generated by default as identity,
    email    varchar(30) not null,
    name     varchar(30) not null,
    password varchar(80) not null
);

create table if not exists topics
(
    id   bigint primary key generated by default as identity,
    name varchar(50) not null
);

create table if not exists users_topics
(
    user_id  bigint,
    topic_id bigint,
    primary key (user_id, topic_id),
    foreign key (user_id) references users (id),
    foreign key (topic_id) references topics (id)
);

create table if not exists files
(
    id       bigint primary key generated by default as identity,
    key     varchar(50) not null,
    owner_id bigint      not null,
    foreign key (owner_id) references users (id)
);